### ISSUE TITLE
请问标注工具用哪个？

### ISSUE THREAD

**Issue by gongel** [BossZard/rotation-yolov5#1]
我尝试了[https://github.com/chinakook/labelImg2](https://github.com/chinakook/labelImg2)，只能拿到angle，好像和文中的尺寸也对不上

**Comment by BossZard** [comment]
这个需要自己进行后处理，生成适合该模型的输入数据。

**Comment by gengyanlei** [comment]
https://github.com/ZeroE04/R-CenterNet/issues/37#issue-834331029
这个labelimg2的角度定义有疑义，所以处理起来需要谨慎。

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/111946769-1eab8d00-8b17-11eb-80ac-2315282de906.png)

而且你这里是1024*1024的图像尺寸，并不是所有图像都是这样的尺寸，那么xywh-angle，w是长边，是有可能大于1的

**Comment by BossZard** [comment]
这个文件仅是针对我自己的数据集写的，事实上你们需要自己按照readme介绍的数据格式自己重写



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gengyanlei ***@***.***&gt;
发送时间: 2021年3月22日 14:02
收件人: BossZard/rotation-yolov5 ***@***.***&gt;
抄送: BossZard ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[BossZard/rotation-yolov5] 请问标注工具用哪个？ (#1)





 

 
而且你这里是1024*1024的图像尺寸，并不是所有图像都是这样的尺寸，那么xywh-angle，w是长边，是有可能大于1的
