### ISSUE TITLE
角度问题

### ISSUE THREAD

**Issue by 992355092** [BossZard/rotation-yolov5#13]
请问下你使用分类的方法求目标的角度吗？0-180°对应180个类别

**Comment by BossZard** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 992355092 ***@***.***&gt;
发送时间: 2021年3月11日 11:21
收件人: BossZard/rotation-yolov5 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[BossZard/rotation-yolov5] 角度问题 (#13)





 
请问下你使用分类的方法求目标的角度吗？0-180°对应180个类别
