### ISSUE TITLE
the definition of angle?

### ISSUE THREAD

**Issue by cs-heibao** [BossZard/rotation-yolov5#14]
the longside clockwise to x-axis is positive angle?
the final angle is the longside to x-axis and then add 90?
so the final angle of the three example you gave is 0+90, 40+90, -90+90, is this right?

**Comment by cs-heibao** [comment]
I got it, thanks.

**Comment by LeCongThuong** [comment]
Hi @cs-heibao!
What range should theta be in the annotation file? [-90, 90) or [0, 180) 
Is clockwise angle between x-axis and longside of rotated rectangle positive?
