### ISSUE TITLE
retanglelabel2mylabel.py

### ISSUE THREAD

**Issue by wangning7149** [BossZard/rotation-yolov5#2]
请问 retanglelabel2mylabel.py，w，h是不是写反了？还有原始图片是不是必须得是长方形？

**Comment by BossZard** [comment]
w,h只是一个变量，名字是什么没关系，只要第一个参数的长边，第二个参数是短边就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BossZard/rotation-yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月2日(星期六) 晚上8:28
收件人:&nbsp;"BossZard/rotation-yolov5"<rotation-yolov5@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[BossZard/rotation-yolov5] retanglelabel2mylabel.py (#2)





 
请问 retanglelabel2mylabel.py，w，h是不是写反了？还有原始图片是不是必须得是长方形？
