### ISSUE TITLE
数据集制作

### ISSUE THREAD

**Issue by Jihnjockey** [BossZard/rotation-yolov5#20]
你好，我想问一下，标签文件里 cx,cy,w,h 是怎么算出来的，网上的数据标签处理只是针对无旋转的YOLOv5，现在我训练出来的结果很差，，基本都不能看，所以我怀疑是数据集制作的问题
![image](https://user-images.githubusercontent.com/53632794/118270543-ca0f0780-b4f2-11eb-9f32-3f00ee59d3a9.png)

**Comment by wenyishengkingkong** [comment]
我想回答一下，不知道对不对，我先用rolabelimg标注了旋转框，约定是将长边和x轴相互重合，然后旋转，并保存。再用rolabelimg_transform里面的格式，修改应该是作者要求的格式（cls,框的x/图像w,框的y/图像的h,框的w/图像的w(因为我默认的长边是w),框的h/图像的h，角度按照作者的要求继续转换 ）我也不知道对不对，觉得逻辑应该是对的。有需要的交流的可以加我qq:118598273

**Comment by Jihnjockey** [comment]
> 我想回答一下，不知道对不对，我先用rolabelimg标注了旋转框，约定是将长边和x轴相互重合，然后旋转，并保存。再用rolabelimg_transform里面的格式，修改应该是作者要求的格式（cls,框的x/图像w,框的y/图像的h,框的w/图像的w(因为我默认的长边是w),框的h/图像的h，角度按照作者的要求继续转换 ）我也不知道对不对，觉得逻辑应该是对的。有需要的交流的可以加我qq:1185968273

**Comment by Jihnjockey** [comment]
> 我想回答一下，不知道对不对，我先用rolabelimg标注了旋转框，约定是将长边和x轴相互重合，然后旋转，并保存。再用rolabelimg_transform里面的格式，修改应该是作者要求的格式（cls,框的x/图像w,框的y/图像的h,框的w/图像的w(因为我默认的长边是w),框的h/图像的h，角度按照作者的要求继续转换 ）我也不知道对不对，觉得逻辑应该是对的。有需要的交流的可以加我qq:1185968273

兄弟  ，你qq号我搜不到。我不明白中心点cx和cy为什么也要除以w和h，你按照这样的处理训练出来的结果怎么样呢
