### ISSUE TITLE
一个BUG？

### ISSUE THREAD

**Issue by Lai898821381** [BossZard/rotation-yolov5#4]
https://github.com/BossZard/rotation-yolov5/blob/f68d7cc8aab089fbdd707bd702d1037e092c1ce5/utils/general.py#L533
这里设置了ttheta的形状，应该是根据后面的 t = torch.full_like(ps[:, 5:10], cn, device=device)来设置的
这里的t是设置为跟cls形状相同，但是默认固定为原始的5个类别，所以如果只是修改了yaml里的类别为其他，而不修改这里就会报错，这里是不是要修改一下弄成跟yaml联系才行
我在打算把这个模型用在我的自定义数据集上发现了这个问题，我是只有一个类别要识别的，我是最近才接触的目标检测，如果是我理解错了，希望能提出纠正一下。

**Comment by BossZard** [comment]
好像是的，打比赛的时候为了节省时间没注意



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lai898821381 <notifications@github.com&gt;
发送时间: 2021年1月4日 12:15
收件人: BossZard/rotation-yolov5 <rotation-yolov5@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[BossZard/rotation-yolov5] 一个BUG？ (#4)





 
https://github.com/BossZard/rotation-yolov5/blob/f68d7cc8aab089fbdd707bd702d1037e092c1ce5/utils/general.py#L533
 这里设置了ttheta的形状，应该是根据后面的 t = torch.full_like(ps[:, 5:10], cn, device=device)来设置的
 这里的t是设置为跟cls形状相同，但是默认固定为原始的5个类别，所以如果只是修改了yaml里的类别为其他，而不修改这里就会报错，这里是不是要修改一下弄成跟yaml联系才行
 我在打算把这个模型用在我的自定义数据集上发现了这个问题，我是只有一个类别要识别的，我是最近才接触的目标检测，如果是我理解错了，希望能提出纠正一下。

**Comment by BossZard** [comment]
感谢发现，已改



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lai898821381 <notifications@github.com&gt;
发送时间: 2021年1月4日 12:15
收件人: BossZard/rotation-yolov5 <rotation-yolov5@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[BossZard/rotation-yolov5] 一个BUG？ (#4)





 
https://github.com/BossZard/rotation-yolov5/blob/f68d7cc8aab089fbdd707bd702d1037e092c1ce5/utils/general.py#L533
 这里设置了ttheta的形状，应该是根据后面的 t = torch.full_like(ps[:, 5:10], cn, device=device)来设置的
 这里的t是设置为跟cls形状相同，但是默认固定为原始的5个类别，所以如果只是修改了yaml里的类别为其他，而不修改这里就会报错，这里是不是要修改一下弄成跟yaml联系才行
 我在打算把这个模型用在我的自定义数据集上发现了这个问题，我是只有一个类别要识别的，我是最近才接触的目标检测，如果是我理解错了，希望能提出纠正一下。

**Comment by Lai898821381** [comment]
你这个修改是简单的删去了角度吗？我是打算用带角度的YOLOV5的，但是我看到修改BUG后的版本是删掉了角度，那这样岂不是对不上原来的那个数据集了，因为原来的数据集格式最后面是有角度的，这样又变回最原来的YOLOV5了吗

**Comment by BossZard** [comment]
刚上传错了，现在应该好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BossZard/rotation-yolov5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 下午3:40
收件人:&nbsp;"BossZard/rotation-yolov5"<rotation-yolov5@noreply.github.com&gt;;
抄送:&nbsp;"梁同学"<804072710@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BossZard/rotation-yolov5] 一个BUG？ (#4)





 
你这个修改是简单的删去了角度吗？我是打算用带角度的YOLOV5的，但是我看到修改BUG后的版本是删掉了角度，那这样岂不是对不上原来的那个数据集了，因为原来的数据集格式最后面是有角度的，这样又变回最原来的YOLOV5了吗
