### ISSUE TITLE
预训练有关事宜

### ISSUE THREAD

**Issue by Lai898821381** [BossZard/rotation-yolov5#7]
你好，我在查看了你的代码之后，发现你的代码似乎不适合用作预训练使用
rotation-yolov5中的最后一维是[x,y,w,h,class_num(5),angle(180)]
如果我的class_num n<5，我的输出变为[x,y,w,h,class_num(n),angle(180)]那么前4+n维都是正确的,用于预测xywh和class，但是后面[4+n:4+n+180]将使用原来用于预测类和角度的维度作为预训练，而不是使用原来的后180个维度作为预训练，似乎不符合预训练的原理。
所以应该将代码修改为[x,y,w,h,angle(180),class_num]
不知道我的理解是否正确，如果正确的话，我想将COCO数据集进行旋转之后获得一个合适的数据集，将rotation-yolov5在上面训练得到一个预训练模型，然后再在我的数据集上进行训练，这个想法是正确的吗？

**Comment by Lai898821381** [comment]
还有就是utils.common.NMS里的forward是返回的原始的non_max_suppression而不是rotation_ non_max_suppression，这个是BUG吗？还是就是你设计的模型里仍然使用原始的non_max_suppression，最后就是你好像只修改了rotation_non_max_suppression，但是实际上在utils.common.NMS里forward的utils.general.non_max_suppression里你还是用的5:10，而不是5:5+class_num

**Comment by BossZard** [comment]
请自行理解backbone，neck，和head，以及finetune的目的。另外其它一些bug可以自己在代码上修改，我不一定有时间马上resotre上到git



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lai898821381 <notifications@github.com&gt;
发送时间: 2021年1月10日 15:10
收件人: BossZard/rotation-yolov5 <rotation-yolov5@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[BossZard/rotation-yolov5] 预训练有关事宜 (#7)





 
你好，我在查看了你的代码之后，发现你的代码似乎不适合用作预训练使用
 rotation-yolov5中的最后一维是[x,y,w,h,class_num(5),angle(180)]
 如果我的class_num n<5，我的输出变为[x,y,w,h,class_num(n),angle(180)]那么前4+n维都是正确的,用于预测xywh和class，但是后面[4+n:4+n+180]将使用原来用于预测类和角度的维度作为预训练，而不是使用原来的后180个维度作为预训练，似乎不符合预训练的原理。
 所以应该将代码修改为[x,y,w,h,angle(180),class_num]
 不知道我的理解是否正确，如果正确的话，我想将COCO数据集进行旋转之后获得一个合适的数据集，将rotation-yolov5在上面训练得到一个预训练模型，然后再在我的数据集上进行训练，这个想法是正确的吗？
